### ISSUE TITLE
Should not use the term "Open Source"

### ISSUE THREAD

**Issue by ghost** [subc/cf_recommender#1]
The license is not "Open Source" 

> No Discrimination Against Fields of Endeavor
> 
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.
> 
> Rationale: The major intention of this clause is to prohibit license traps that prevent open source from being used commercially. We want commercial users to join our community, not feel excluded from it.

https://opensource.org/osd-annotated
Japanese one http://www.opensource.jp/osd/osd-japanese.html

Your license requires payment for business use, it's one of restrictions.

**Comment by ghost** [comment]
The artile on Qiita also includes the term "オープンソース" http://qiita.com/haminiku/items/0cdf006d667ef8a7494e

**Comment by hirokiky** [comment]
My suggestion is to make the project as MIT License, and add "Donation" button to the README page. 
I think this product is awesome, so I want it to be actual "Open Source".

**Comment by subc** [comment]
change license. enjoy captain!
